# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-15 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author_profile',
        ),
    ]
