# Generated by Django 4.0.4 on 2022-06-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0003_projects_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcategory', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardapp.category'),
        ),
    ]
