# Generated by Django 4.0.4 on 2022-06-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0004_category_alter_projects_projectcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='projectcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectcategory',
            new_name='category',
        ),
    ]
