# Generated by Django 4.0.4 on 2022-06-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0005_rename_projectcategory_category_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='ecommerce',
        ),
        migrations.AddField(
            model_name='category',
            name='landingpage',
            field=models.CharField(default='landingpage', max_length=80),
        ),
    ]
