# Generated by Django 4.0.4 on 2022-06-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0006_rename_category_category_ecommerce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='landingpage',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='awardapp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
