# Generated by Django 4.0.4 on 2022-06-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0007_remove_category_landingpage_category_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ecommerce',
            new_name='name',
        ),
    ]
