# Generated by Django 4.0.4 on 2022-06-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0008_rename_ecommerce_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
