# Generated by Django 4.0.4 on 2022-06-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0010_remove_projects_slug_alter_projects_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category',
            new_name='projectcategory',
        ),
    ]
