# Generated by Django 4.0.4 on 2022-08-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Say_Something',
        ),
    ]
